# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      # ソースコードのチェックアウト
      - checkout
      # unittestコマンドの実行
      - run: python test_calculation.py